import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const PSL_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';
const OUTPUT_FILE = resolve(import.meta.dir, '../src/suffixes.ts');

console.log('Fetching official Public Suffix List from:', PSL_URL);
const response = await fetch(PSL_URL);
if (!response.ok) {
  throw new Error(`Failed to fetch PSL: ${response.status} ${response.statusText}`);
}

const text = await response.text();
const lines = text.split('\n');

const suffixes = new Set<string>();
let inIcann = false;

for (const line of lines) {
  const trimmed = line.trim();
  if (trimmed.includes('===BEGIN ICANN DOMAINS===')) {
    inIcann = true;
    continue;
  }
  if (trimmed.includes('===END ICANN DOMAINS===')) {
    inIcann = false;
    break;
  }
  if (!inIcann || !trimmed || trimmed.startsWith('//')) continue;

  const clean = trimmed.replace(/^[*!]\./, '').toLowerCase();
  const parts = clean.split('.');
  if (parts.length >= 2 && parts.length <= 4 && !parts.some((p) => !p)) {
    suffixes.add(clean);
  }
}

// Add common multi-tenant apex hosting platforms
suffixes.add('github.io');
suffixes.add('gitlab.io');
suffixes.add('pages.dev');
suffixes.add('vercel.app');
suffixes.add('web.app');

const sorted = [...suffixes].sort();

console.log(`Extracted ${sorted.length} official multi-level (2, 3, 4) suffixes.`);

const outputCode = `// Auto-generated by scripts/generate-suffixes.ts from Mozilla Public Suffix List.
// Total rules (Levels 2, 3, 4): ${sorted.length}
export const PUBLIC_SUFFIXES: Set<string> = new Set(${JSON.stringify(sorted, null, 2)});
export const TWO_LEVEL_SUFFIXES = PUBLIC_SUFFIXES;
`;

writeFileSync(OUTPUT_FILE, outputCode, 'utf8');
console.log(`Successfully generated: ${OUTPUT_FILE}`);
